version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    environment:
      - SAAS_MANAGER_HOST=$SAAS_MANAGER_HOST
      - USER_MANAGER_HOST=$USER_MANAGER_HOST
      - DEFAULT_FROM_EMAIL=noreply@example.com
      - OPENEXCHANGERATES_API_KEY
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=False
      - JWT_VERIFY_EXPIRATION=True
      - VATLAYER_ACCESS_KEY
    depends_on:
      - db
      - redis

  db:
    image: library/postgres:11.1-alpine
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
  
  redis:
    image: library/redis:5.0-alpine
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
      - saleor-redis:/data

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        STATIC_URL: '/static/'
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    env_file: common.env
    depends_on:
      - redis

volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local

networks:
  saleor-backend-tier:
    driver: bridge
